export interface IndicatorWeight {
  id: string;
  name: string;
  weight: number;
  rank: number;
  description: string;
  dataSource?: string;
  isLive?: boolean;
}

export const INDICATOR_WEIGHTS: IndicatorWeight[] = [
  {
    id: 'pi-cycle',
    name: 'Pi Cycle Top Indicator',
    weight: 0.30,
    rank: 1,
    description: '111DMA crossing 350DMA×2 signals cycle tops',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'mvrv',
    name: 'MVRV Ratio',
    weight: 0.28,
    rank: 2,
    description: 'Market Value / Realized Value ratio',
    dataSource: 'Mock Data',
    isLive: false,
  },
  {
    id: 's2f',
    name: 'Stock-to-Flow Model',
    weight: 0.22,
    rank: 3,
    description: 'Scarcity-based valuation model',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'lth-supply',
    name: 'Long-Term Holder Supply',
    weight: 0.18,
    rank: 4,
    description: 'Coins held >155 days',
    dataSource: 'Mock Data',
    isLive: false,
  },
  {
    id: 'puell',
    name: 'Puell Multiple',
    weight: 0.16,
    rank: 5,
    description: 'Daily issuance value / 365-day MA',
    dataSource: 'Mock Data',
    isLive: false,
  },
  {
    id: 'nvt',
    name: 'NVT Ratio',
    weight: 0.13,
    rank: 6,
    description: 'Network Value to Transactions',
    dataSource: 'Blockchain.info',
    isLive: true,
  },
  {
    id: 'etf-flows',
    name: 'Bitcoin ETF Flows',
    weight: 0.15,
    rank: 7,
    description: 'Institutional demand tracking',
    dataSource: 'Yahoo Finance',
    isLive: true,
  },
  {
    id: 'exchange-reserves',
    name: 'Exchange Reserves',
    weight: 0.12,
    rank: 8,
    description: 'Bitcoin held on exchanges',
    dataSource: 'Blockchain.info',
    isLive: true,
  },
  {
    id: 'mpi',
    name: 'Miner Position Index',
    weight: 0.10,
    rank: 9,
    description: 'Miner selling pressure',
    dataSource: 'Mock Data',
    isLive: false,
  },
  {
    id: 'fear-greed',
    name: 'Fear & Greed Index',
    weight: 0.08,
    rank: 10,
    description: 'Market sentiment indicator',
    dataSource: 'Alternative.me',
    isLive: true,
  },
  {
    id: 'btc-dominance',
    name: 'Bitcoin Dominance',
    weight: 0.07,
    rank: 11,
    description: 'BTC market cap percentage',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'funding-rates',
    name: 'Funding Rates',
    weight: 0.06,
    rank: 12,
    description: 'Perpetual futures funding',
    dataSource: 'Binance/Bybit',
    isLive: true,
  },
  {
    id: 'coinbase-premium',
    name: 'Global Premium',
    weight: 0.05,
    rank: 13,
    description: 'US/Global price premium',
    dataSource: 'Multi-Exchange',
    isLive: true,
  },
  {
    id: 'rainbow',
    name: 'Rainbow Chart',
    weight: 0.04,
    rank: 14,
    description: 'Logarithmic growth bands',
    dataSource: 'Mock Data',
    isLive: false,
  },
  {
    id: 'hash-ribbons',
    name: 'Hash Ribbons',
    weight: 0.03,
    rank: 15,
    description: 'Mining hash rate signals',
    dataSource: 'Blockchain.info',
    isLive: true,
  },
  {
    id: 'lightning-network',
    name: 'Lightning Network',
    weight: 0.02,
    rank: 16,
    description: 'Layer 2 adoption metrics',
    dataSource: 'Mempool.space',
    isLive: true,
  },
  {
    id: 'market-depth',
    name: 'Market Depth',
    weight: 0.08,
    rank: 17,
    description: 'Order book bid/ask ratio',
    dataSource: 'Binance',
    isLive: true,
  },
  {
    id: 'ath-distance',
    name: 'ATH Distance',
    weight: 0.10,
    rank: 18,
    description: 'Distance from all-time high',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'volume-trend',
    name: 'Volume Trend',
    weight: 0.08,
    rank: 19,
    description: '24h vs 30d average volume',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'momentum-30d',
    name: '30-Day Momentum',
    weight: 0.07,
    rank: 20,
    description: '30-day price momentum',
    dataSource: 'CoinGecko',
    isLive: true,
  },
  {
    id: 'fee-pressure',
    name: 'Fee Pressure',
    weight: 0.05,
    rank: 21,
    description: 'Network fee pressure',
    dataSource: 'Mempool.space',
    isLive: true,
  },
  {
    id: 'network-congestion',
    name: 'Network Congestion',
    weight: 0.05,
    rank: 22,
    description: 'Mempool congestion level',
    dataSource: 'Mempool.space',
    isLive: true,
  },
  {
    id: 'miner-revenue',
    name: 'Miner Revenue',
    weight: 0.04,
    rank: 23,
    description: 'Total miner revenue',
    dataSource: 'Blockchain.info',
    isLive: true,
  },
  {
    id: 'difficulty-adjustment',
    name: 'Difficulty Adjustment',
    weight: 0.03,
    rank: 24,
    description: 'Mining difficulty change',
    dataSource: 'Blockchain.info',
    isLive: true,
  },
];

// Normalize weights to ensure they sum to 1
const totalWeight = INDICATOR_WEIGHTS.reduce((sum, ind) => sum + ind.weight, 0);
INDICATOR_WEIGHTS.forEach(ind => {
  ind.weight = ind.weight / totalWeight;
});